@url_dev = http://localhost:3010/v1/api
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdDlAZ21haWwuY29tIiwiaWF0IjoxNzE1ODgwMDIzLCJleHAiOjE3MTY0ODQ4MjN9.pt7Y4oKxT9SX8nz7SDnt95RHJ5ZUgVMil74j2qI4y_XGcTXdqb3KPB1Pxf8H6jTX2mIibUEYRuDFufuaewOeoaGk4pwis_A3Z7WCqelF04vnwgL8BLUtK-FNysi16Gct6HKmvmORasc3rkbMvKaJEbFXrnHhp_nrpLQQEFJVfqru1ubjdnjfjzMYakI0JK_CAhUjOb6wIOEaSW7A_X8qFDlJlJz3p1q2nR_mak3x6X-b4ShXcSicAhJcifkmv1TuyxHfnxW1JWHWxbLrEG1WsfRS3ODhArYTOmcV5Kg-Oluu6F6--j51fN4JFIqiSmFhDo-7prN8Wz0HziuV8hHulQ
@userId = 657241821e3a2f6841b07a2c
@apiKey = b6978370f03fe98bb4f280dc141b1ae2e0acff093965996f61aeee3bcc28c5c33f9254349838e91f3edd1a98b831dd7e5d6ee899e9dd0e36b8c6a32aba1b146a

### signup
POST {{url_dev}}/signup
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "name": "admin",
  "email": "test@gmail.com",
  "password": "123"
}

### login
POST {{url_dev}}/login
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "email": "test9@gmail.com",
  "password": "123"
}

### logout
POST {{url_dev}}/logout
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdDlAZ21haWwuY29tIiwiaWF0IjoxNzE1ODgxMDAwLCJleHAiOjE3MTU4ODEwMDF9.bWyDPJw9pHzbmCCGG55vC0Ljh5kHkKU8BUoFeRJhD3a9t2V_T3F93rwYgicDveKauNDq3QO-JVVSh2HGd2-MNIGGfkY0lcdfTF_i3UG5uF_RI6C-kOi672PgGk1VBszyvBsMzGeydGn2dRpTTDtFGT0bThv5ZIg3xTd36ac8Y9sonfdOGHBcAV0ybmEDkG7zhiYwE11NWNnOw-wBu73vpz8qoozc1BKmSQbkLzJOWD26kCOAy6MfXM17QTmJwyfAHu9lpKlaKULI92iT5SWSkLIKrxoEPIuDAT7MXU6gCDMRDnEuvOpufltw1NHf0mR6R46NeVjzK6Wp_tvjQqCeaw

### refresh token
POST {{url_dev}}/refresh-token
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTcyNDE4MjFlM2EyZjY4NDFiMDdhMmMiLCJlbWFpbCI6InRlc3Q5QGdtYWlsLmNvbSIsImlhdCI6MTcwMjQ3NjM1OSwiZXhwIjoxNzAzMDgxMTU5fQ.2DDoCbdK3vPOuB9q3_h06g2leJ-BSEtiioHxtFSJ2po"
}