# @url_dev = http://localhost:3010/api/v1
@url_dev = https://api.qspeco.com/api/v1
# @accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhODAzMTViNy0wMjI1LTQzZTMtOGZiYi0yZmMzYzVkMWNlNzciLCJ1c2VybmFtZSI6InVzZXIyIiwiaWF0IjoxNzE4ODYxMDkxfQ.O-f5iSkqJc40qywpAW8AJhoMj-l2ambj2sIzAAANobpHXqRtrXq4miRhvHIyqviw_r41Z8byDgkai06JYsrUAvWHAFwqeplr544Gj8oupRuKGLKBYBr6qALdln6DhFQNCXrZ3oGaSmJp3Jxk2wLHnZ8LELmYrBTN1-QmEjXTr1tS8EZ-2tqYqatR579Dzlo8k2hkhsi1h46ZZ-3TxBHGEF4NAiXrCGXfUfxXeQZqe1BIBMcKVH-EGVjYQD4VFPg_JOMHRUDPs6ZXiKw2E4lhQhDCCMKcY80ySktJbJbNGbt7WdPdovgiltqC8M2pGyDNL699Vsyt0Gp3nclR45KuLw
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5OGM4N2Y0Zi1mYWQyLTQ4YjctODlkNy0zZTg3ZTQ2OGEyYTIiLCJ1c2VybmFtZSI6ImFkbWluc3RvcmUzIiwiaWF0IjoxNzE4ODYzMTg4fQ.o-larvVK5wjoNwDUov7vkqYp6_F2OLek6K1UvkZMcvj3iauyRWWxUfDgWZSQKK8AoSapgg6t8Hy0QKloVfmi0Uo5UN3Po5hRnbmBI19bDcFAArB961P47ZXvUemvFLr1PJUSnmyICzwdAozxAwOnxJPvF0iSa2v7D995Jfz71nOF7CPcshkGJTlCEroW6khodCH7t9a8pxh-K6ALGl8CLv90Mes2LIkTfIWFSLffg7AfDsc0QUqPdHvMGPIn7Pl1wEY4I3rG8-7mrThZyGlusbMwSFjfN7dY4nI-MtLAHj9_W4UTpCYuYJa5h6bglwJB0BIK8nCRvp5GDuUUpspk0g
@userId = 657241821e3a2f6841b07a2c
@apiKey = b6978370f03fe98bb4f280dc141b1ae2e0acff093965996f61aeee3bcc28c5c33f9254349838e91f3edd1a98b831dd7e5d6ee899e9dd0e36b8c6a32aba1b146a

### signup
POST {{url_dev}}/signup
Content-Type: application/json

{
  "username": "admin",
  "fullname": "Administrator",
  "password": "123"
}

### login
POST {{url_dev}}/login
Content-Type: application/json
# X-API-Key: {{apiKey}}

{
  "username": "adminstore3",
  "password": "123"
}

### logout
POST {{url_dev}}/logout
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### refresh token
POST {{url_dev}}/refresh-token
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTcyNDE4MjFlM2EyZjY4NDFiMDdhMmMiLCJlbWFpbCI6InRlc3Q5QGdtYWlsLmNvbSIsImlhdCI6MTcwMjQ3NjM1OSwiZXhwIjoxNzAzMDgxMTU5fQ.2DDoCbdK3vPOuB9q3_h06g2leJ-BSEtiioHxtFSJ2po"
}

### import invoice
POST {{url_dev}}/invoice/import
Content-Type: application/json
# X-API-Key: {{apiKey}}
# X-Client-ID: {{userId}}
Authorization: {{accessToken}}

{
  "Logger_ID": "01905969501",
  "Check_Key": "T00R00K155628190526",
  "Logger_Time": "14-05-2024 15-55-28",
  "Pump_ID": 1,
  "Bill_No": 23,
  "Bill_Type": 1,
  "Fuel_Type": "XĂNG RON 95 - III",
  "Start_Time": "12-04-2024 16-51-21",
  "End_Time": "12-04-2024 16-52-50",
  "Unit_Price": 25740,
  "Quantity": 0.545,
  "Total_Price": 14020
}

### get invoices
GET {{url_dev}}/invoice/list
Content-Type: application/json
# X-API-Key: {{apiKey}}
# X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### get invoice
GET {{url_dev}}/invoice/23/01905969501
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### edit invoices
POST {{url_dev}}/invoice/43d48534-64e3-44a6-afc5-4cc506e100f3
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### delete invoices
DELETE  {{url_dev}}/invoice/43d48534-64e3-44a6-afc5-4cc506e100f3
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

