# @url_dev = http://localhost:3010/api/v1
@url_dev = https://api.qspeco.com/api/v1
@accessToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MTY4MjZiYy01ZmEwLTQxOWQtODU3NS1kMzNjMTBlMWEwODMiLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzE2Mzk5MjU5fQ.d4BPOiEOlDvXFzCJD9MWaqbT8-Z6n5AKrCvFiXUX8Yj8kbsiuTfNJC2qQ62LUmBU8hWyyzG5hhxi0fWUqMRYIDJaMVjRHEk_nJNidrQIixY-hbthutRkvQ5YtvwTfTGVvsBo3xTOFuo6T58zb4UXORLd-yghm1bPSW0gj0R9GpKe0skYlg3kXPKT32S1W-QAf8XuJf2fxaNzWqWq9zjIFoV8fDwOCTIV7KwoADBMHgM_fEWY4wwmkU7lJxQLmjelKcL28XxWyMeA0dv3qvJHYfCd_Z3p4iGnY4SyTfqmtSHXCYPT0e8y0EeC57iRwQieQyk0-PksH5sJP8IYrCr-Qg
@userId = 657241821e3a2f6841b07a2c
@apiKey = b6978370f03fe98bb4f280dc141b1ae2e0acff093965996f61aeee3bcc28c5c33f9254349838e91f3edd1a98b831dd7e5d6ee899e9dd0e36b8c6a32aba1b146a
//Company B
@companyToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiJkYWY3ODA1MC0zOWQ5LTRmOGItYjM2Mi01NzU3ZGJlODgzZTAiLCJjb21wYW55TmFtZSI6IkNvbXBhbnkgQSIsImlhdCI6MTcxOTkxMDMxNH0.BxT7HuOrv5Yju0PjMdera-bpBNirCmJyXXH-r38MM6nEWPwwm1m8Ox6SYhX4yuw1Rw9AHEibFqa3LDEKSbc9Gw5TFz9FLqK1lYoUOsTKuZYT2GAeo8M9y3dVLpTudJnRJxBrQa7spwF31QZdQiiw7mXLjn7T5lYyPZuDW145snkWQJ1e_6Zp8Htpefu8ystjSbBP4IRoZbTfDqn5vI-t_KPZG5OM3QCYDEJR2C7lPCxtSJ_WHVqamoe1Qkq2Vfp70RjggONjKIMur2vpePW0Nb9OLqUq3l5pwZP7FEtgrE5NuDM5aQF1IwNUjHhvMNvidMODjbxRSFYWBuV-mLfKKA
@companyTokenPeco = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55SWQiOiIwNzVmMDU2My1iNDg1LTQ1NzktODEwZi0xYmVkNTg3Yzc2N2EiLCJjb21wYW55TmFtZSI6IkNvbXBhbnkgQSIsImlhdCI6MTcyMDI1ODk0N30.jfxf7wciicl_fw7LS1eLKI771QUy6qal1OIb8L1Lh96OJ3IuiK1C_9Xk_us7kwsb2QE296KZuv1CwJterl1Avj6Cp2aV7khnRq2KzmeiJDnx4l6xakZLSsLyPpEcIiJU1QTgY7-iEqJZs7gag1DPMatGke5cnYGJbpl8zsr_nOvETAMyTbznRct_AKmWY-TfWDVxQMVBm2cJwv0eCv2TqncilCs1-Gs1OJ1WoVWFgo-Zjodf5D73_Gdl7tzLdPfQ7dMKxFZH_pOv2sqwqbeXN05VW1fXs_vJ14FLo2UqM8fnkYF-esKPbwu0FzhaWEUZz5zUuVZ4FuhRJfQSBv93nw

### import invoice
POST {{url_dev}}/invoice/import
Content-Type: application/json
# X-API-Key: {{apiKey}}
# X-Client-ID: {{userId}}
# Authorization: {{companyToken}}
Authorization: {{companyTokenPeco}}

{
  "Check_Key": "T00R00K071232100724",
  "Logger_ID": "123",
  "Logger_Time": "27-08-2024 08-44-23",
  "Pump_ID": 2,
  "Bill_No": 12,
  "Bill_Type": 1,
  "Fuel_Type": "XĂNG RON 95 - III",
  "Start_Time": "27-08-2024 08-44-23",
  "End_Time": "27-08-2024 08-44-23",
  "Unit_Price": 12,
  "Quantity": 1.84,
  "Total_Price": 2
}

# {
#   Logger_ID: '01905955015',
#   Service_Username: 'xxx',
#   Service_Password: 'xxx',
#   Check_Key: 'T00R00K084423270824',
#   Logger_Time: '27-08-2024 08-44-23',
#   Pump_ID: 0,
#   Bill_No: 74079,
#   Bill_Type: 1,
#   Fuel_Type: 'XĂNG RON 95 - III',
#   Start_Time: '27-08-2024 08-44-23',
#   End_Time: '27-08-2024 08-44-23',
#   Unit_Price: 21730,
#   Quantity: 1.84,
#   Total_Price: 40000
# }
### get invoices
GET {{url_dev}}/invoice/list
Content-Type: application/json
# X-API-Key: {{apiKey}}
# X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### get invoice
GET {{url_dev}}/invoice/23/01905969501
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### edit invoices
POST {{url_dev}}/invoice/43d48534-64e3-44a6-afc5-4cc506e100f3
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

### delete invoices
DELETE  {{url_dev}}/invoice/43d48534-64e3-44a6-afc5-4cc506e100f3
Content-Type: application/json
X-API-Key: {{apiKey}}
X-Client-ID: {{userId}}
Authorization: {{accessToken}}

